/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import deps.preset.bess.v1.ModelV1.*;
import deps.model.pcs.v1.ModelV1.*;

public class Library {
    public boolean someLibraryMethod() {
        BessMeasure measure = BessMeasure.newBuilder().setData(
                Bess.newBuilder().setPcs(ThreePhasePcsPart.newBuilder().build()).build()).build();

        System.out.println(measure);
        return true;
    }
}
