/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import io.github.grida_energy.deps.preset.bess.v1.ModelV1.*;
import io.github.grida_energy.deps.model.pcs.v1.ModelV1.*;

public class Library {
    public boolean someLibraryMethod() {
        BessMeasure measure = BessMeasure.newBuilder().setData(
                Bess.newBuilder().setPcs(ThreePhasePcsPart.newBuilder().setW(50).build()).build()).build();

        System.out.println(measure);
        return true;
    }
}
