/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.0.0/userguide/building_java_projects.html in the Gradle documentation.
 */

// import com.vanniktech.maven.publish.SonatypeHost
import com.vanniktech.maven.publish.KotlinJvm
import com.vanniktech.maven.publish.JavadocJar

plugins {
    // Apply the java-library plugin for API and implementation separation.
    id("java-library")
    id("maven-publish")
    id("signing")
    // id("org.jreleaser") version "1.21.0"
    // kotlin("jvm") version "1.9.20"
    id("org.jetbrains.kotlin.jvm") version "2.3.0"
    id("com.vanniktech.maven.publish") version "0.35.0"
    id("com.google.protobuf") version "0.9.4"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is exported to consumers, that is to say found on their compile classpath.
    api(libs.commons.math3)

    // This dependency is used internally, and not exposed to consumers on their own compile classpath.
    implementation(libs.guava)
    api("com.google.protobuf:protobuf-java:4.26.1")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    // withSourcesJar()
    // withJavadocJar()
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

sourceSets {
    main {
        proto {
            srcDir("$projectDir/../../protos")
            srcDir("build/generated/source/proto/main/java")
        }
    }
}

buildscript {
    dependencies {
        classpath("com.google.protobuf:protobuf-gradle-plugin:0.9.4")
    }
}

tasks {
    // getByName<Delete>("clean") {
    //     // delete.add("$projectDir/src/main/deps")
    //     // delete.add("$projectDir/src/main/grpc")
    //     // delete.add("$projectDir/src/main/java/internal")
    //     // delete.add("$projectDir/src/main/java/io")
    // }
    getByName("processResources") {
        dependsOn("generateProto")
    }
}

protobuf {
    protoc {
        artifact = "com.google.protobuf:protoc:4.26.1"
    }
}


mavenPublishing {
    coordinates(
        groupId = "io.github.grida-energy",
        artifactId = "deps",
        version = "1.0.6"
    )

    configure(KotlinJvm(
        javadocJar = JavadocJar.Javadoc(),
        sourcesJar = true
    ))

    pom {
        name.set("DEPS - Distributed Energy Protocol System")
        description.set("Common data model for distributed energy devices and systems.")
        url.set("https://github.com/grida-energy/deps")

        licenses {
            license {
                name.set("MIT License")
                url.set("https://opensource.org/licenses/MIT")
            }
        }
        developers {
            developer {
                id.set("mark.ahn")
                name.set("Mark Ahn")
                email.set("mark.ahn@gridaenergy.com")
            }
        }
        scm {
            url.set("https://github.com/grida-energy/deps")
            connection.set("scm:git:git://github.com/grida-energy/deps.git")
            developerConnection.set("scm:git:ssh://github.com/grida-energy/deps.git")
        }
    }

    // publishToMavenCentral(SonatypeHost.CENTRAL_PORTAL)
    publishToMavenCentral()
    signAllPublications()
}


// signing {
//     useInMemoryPgpKeys(
//         (project.findProperty("signingKeyId") as String?)
//             ?: System.getenv("SIGNING_KEY_ID"),
//         (project.findProperty("signingKey") as String?)
//             ?: System.getenv("SIGNING_KEY"),
//         (project.findProperty("signingKeyPassword") as String?)
//             ?: System.getenv("SIGNING_KEY_PASSWORD")
//     )
//     sign(publishing.publications["mavenJava"])
// }
