.PHONY: rust python md java js

all: rust python md java js

rust:
	cd rust && make

python:
	cd python && make

md:
	cd md && make

java:
	cd java && make

js:
	cd js && make

clean:
	cd rust && make clean
	cd python && make clean
	cd md && make clean
	cd java && make clean
	cd js && make clean
