.PHONY: rust python md java

all: rust python md java

rust:
	cd rust && make

python:
	cd python && make

md:
	cd md && make

java:
	cd java && make

clean:
	cd rust && make clean
	cd python && make clean
	cd md && make clean
	cd java && make clean